### ISSUE TITLE
Error in DQN-in-R/Memory.R 

### ISSUE THREAD

**Issue by laz8** [kkweon/DQN-in-R#1]
if (self$length > self$capacity) {
                self$states <- self$states[2:self$length, ] # states has now length 2:length
                self$actions <- matrix(self$actions[2:self$length, ])
                self$rewards <- matrix(self$rewards[2:self$length, ])
                self$dones <- matrix(self$dones[2:self$length, ])
                self$states2 <- self$states[2:self$length, ] # wrong, states is shorter now
                
                self$length <- self$length - 1L
            }

corrected

            if (self$length > self$capacity) {
                self$states <- self$states[2:self$length, ] # states has now length 2:length
                self$actions <- matrix(self$actions[2:self$length, ])
                self$rewards <- matrix(self$rewards[2:self$length, ])
                self$dones <- matrix(self$dones[2:self$length, ])
                self$states2 <- self$states2[2:self$length, ] # states2 is correct here
                
                self$length <- self$length - 1L
            }

**Comment by kkweon** [comment]
You're right. Thank you for finding it out.

**Comment by laz8** [comment]
you're welcome ;)

thank you for giving your knowledge to the public!
